This notebook builds an dataset (from 2 sub-datasets) used for path-based view mainly used for cancelled flights used in Tableau presentation

In [1]:
import pandas as pd

In [2]:
#df1 = pd.read_csv('data/2008.csv', nrows=10000, encoding='latin-1')
df1 = pd.read_csv('data/2008.csv', nrows=None, encoding='latin-1')

In [3]:
df1.head(8).T

,0,1,2,3,4,5,6,7
Year,2008,2008,2008,2008,2008,2008,2008,2008
Month,1,1,1,1,1,1,1,1
DayofMonth,3,3,3,3,3,3,3,3
DayOfWeek,4,4,4,4,4,4,4,4
DepTime,2003,754,628,926,1829,1940,1937,1039
CRSDepTime,1955,735,620,930,1755,1915,1830,1040
ArrTime,2211,1002,804,1054,1959,2121,2037,1132
CRSArrTime,2225,1000,750,1100,1925,2110,1940,1150
UniqueCarrier,WN,WN,WN,WN,WN,WN,WN,WN
FlightNum,335,3231,448,1746,3920,378,509,535
TailNum,N712SW,N772SW,N428WN,N612SW,N464WN,N726SW,N763SW,N428WN
ActualElapsedTime,128,128,96,88,90,101,240,233
CRSElapsedTime,150,145,90,90,90,115,250,250
AirTime,116,113,76,78,77,87,230,219
ArrDelay,-14,2,14,-6,34,11,57,-18
DepDelay,8,19,8,-4,34,25,67,-1
Origin,IAD,IAD,IND,IND,IND,IND,IND,IND
Dest,TPA,TPA,BWI,BWI,BWI,JAX,LAS,LAS
Distance,810,810,515,515,515,688,1591,1591
TaxiIn,4,5,3,3,3,4,3,7
TaxiOut,8,10,17,7,10,10,7,7
Cancelled,0,0,0,0,0,0,0,0
CancellationCode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Diverted,0,0,0,0,0,0,0,0
CarrierDelay,NaN,NaN,NaN,NaN,2,NaN,10,NaN
WeatherDelay,NaN,NaN,NaN,NaN,0,NaN,0,NaN
NASDelay,NaN,NaN,NaN,NaN,0,NaN,0,NaN
SecurityDelay,NaN,NaN,NaN,NaN,0,NaN,0,NaN
LateAircraftDelay,NaN,NaN,NaN,NaN,32,NaN,47,NaN

In [4]:
#dfclean = old[['A', 'C', 'D']].copy()

In [5]:
df2 = pd.read_csv('data/airports.csv', nrows=None, encoding='latin-1')

In [6]:
df2.head(8).T

,0,1,2,3,4,5,6,7
iata,00M,00R,00V,01G,01J,01M,02A,02C
airport,Thigpen,Livingston Municipal,Meadow Lake,Perry-Warsaw,Hilliard Airpark,Tishomingo County,Gragg-Wade,Capitol
city,Bay Springs,Livingston,Colorado Springs,Perry,Hilliard,Belmont,Clanton,Brookfield
state,MS,TX,CO,NY,FL,MS,AL,WI
country,USA,USA,USA,USA,USA,USA,USA,USA
lat,31.9538,30.6859,38.9457,42.7413,30.688,34.4917,32.8505,43.0875
long,-89.2345,-95.0179,-104.57,-78.0521,-81.9059,-88.2011,-86.6115,-88.1779

In [7]:
# Unify column name convention
df2.columns = ['Iata', 'Airport', 'City', 'State', 'Country', 'Latitude', 'Longitude']

In [8]:
df2.head(8).T

,0,1,2,3,4,5,6,7
Iata,00M,00R,00V,01G,01J,01M,02A,02C
Airport,Thigpen,Livingston Municipal,Meadow Lake,Perry-Warsaw,Hilliard Airpark,Tishomingo County,Gragg-Wade,Capitol
City,Bay Springs,Livingston,Colorado Springs,Perry,Hilliard,Belmont,Clanton,Brookfield
State,MS,TX,CO,NY,FL,MS,AL,WI
Country,USA,USA,USA,USA,USA,USA,USA,USA
Latitude,31.9538,30.6859,38.9457,42.7413,30.688,34.4917,32.8505,43.0875
Longitude,-89.2345,-95.0179,-104.57,-78.0521,-81.9059,-88.2011,-86.6115,-88.1779

In [9]:
# Build FlightPaths view for map visualization in Tableau (2 datapoints per each path: From-To)
path_id = 0
items = []

# For each row
for index, row in df1.iterrows():
    #print("Original: ", row['Origin'], row['Dest'])
    path_id = path_id + 1
    delayed = 0
    if row['ArrDelay'] > 15: delayed = 1
    
    items.append({
        'PathId': path_id,
        'PointOrder': 1,
        'Iata': row['Origin'],
        'Cancelled': row['Cancelled'],
        'Delayed': delayed,
        'From': row['Origin'],
        'To': row['Dest']
    })
    
    items.append({
        'PathId': path_id,
        'PointOrder': 2,
        'Iata': row['Dest'],
        'Cancelled': row['Cancelled'],
        'Delayed': delayed,
        'From': row['Origin'],
        'To': row['Dest']
    })
    
#df['Path_Id'] = index
df = pd.DataFrame(items, columns = ['PathId', 'PointOrder', 'Iata', 'Cancelled', 'Delayed', 'From', 'To'])
df.head(10)

   PathId  PointOrder Iata  Cancelled  Delayed From   To
0       1           1  IAD          0        0  IAD  TPA
1       1           2  TPA          0        0  IAD  TPA
2       2           1  IAD          0        0  IAD  TPA
3       2           2  TPA          0        0  IAD  TPA
4       3           1  IND          0        0  IND  BWI
5       3           2  BWI          0        0  IND  BWI
6       4           1  IND          0        0  IND  BWI
7       4           2  BWI          0        0  IND  BWI
8       5           1  IND          0        1  IND  BWI
9       5           2  BWI          0        1  IND  BWI

In [10]:
# Inner join df and df2 on Iata
#df_out = pd.merge(left=df, right=df2, how='inner', on='Iata').sort_values('PathId')
df_out = pd.merge(left=df, right=df2, how='inner', on='Iata')
df_out.info(null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14019456 entries, 0 to 14019455
Data columns (total 13 columns):
PathId        14019456 non-null int64
PointOrder    14019456 non-null int64
Iata          14019456 non-null object
Cancelled     14019456 non-null int64
Delayed       14019456 non-null int64
From          14019456 non-null object
To            14019456 non-null object
Airport       14019456 non-null object
City          14009907 non-null object
State         14009907 non-null object
Country       14019456 non-null object
Latitude      14019456 non-null float64
Longitude     14019456 non-null float64
dtypes: float64(2), int64(4), object(7)
memory usage: 1.5+ GB

In [11]:
# Add PathName
df_out['PathName'] = df_out['From'] + '->' + df_out['To']

In [12]:
df_out.sort_values('PathId').head(10)

,PathId,PointOrder,Iata,Cancelled,Delayed,From,To,Airport,City,State,Country,Latitude,Longitude,PathName
0,1,1,IAD,0,0,IAD,TPA,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.455810,IAD->TPA
152053,1,2,TPA,0,0,IAD,TPA,Tampa International,Tampa,FL,USA,27.975472,-82.533250,IAD->TPA
1,2,1,IAD,0,0,IAD,TPA,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.455810,IAD->TPA
152054,2,2,TPA,0,0,IAD,TPA,Tampa International,Tampa,FL,USA,27.975472,-82.533250,IAD->TPA
393885,3,2,BWI,0,0,IND,BWI,Baltimore-Washington International,Baltimore,MD,USA,39.175402,-76.668198,IND->BWI
308403,3,1,IND,0,0,IND,BWI,Indianapolis International,Indianapolis,IN,USA,39.717329,-86.294384,IND->BWI
393886,4,2,BWI,0,0,IND,BWI,Baltimore-Washington International,Baltimore,MD,USA,39.175402,-76.668198,IND->BWI
308404,4,1,IND,0,0,IND,BWI,Indianapolis International,Indianapolis,IN,USA,39.717329,-86.294384,IND->BWI
393887,5,2,BWI,0,1,IND,BWI,Baltimore-Washington International,Baltimore,MD,USA,39.175402,-76.668198,IND->BWI
308405,5,1,IND,0,1,IND,BWI,Indianapolis International,Indianapolis,IN,USA,39.717329,-86.294384,IND->BWI

In [13]:
df_out.to_csv('data/FlighPaths2008.csv', index=False)

In [14]:
# Used later to aggregate flight connections
df_out['Total'] = 1 # to summarize total flight for one direction
df_out['Problematic'] = 0 # to count problematic flights

In [15]:
# Populate Problematic with 1 if Cancelled or Delayed
df_out.loc[(df_out['Cancelled'] == 1) | (df_out['Delayed'] == 1), ['Problematic']] = 1

In [16]:
#df_out[df_out["Iata"] == 'IAD' and df_out['PointOrder'] == 1]

mask = ((df_out.Iata == 'IAD') & (df_out.Delayed == 1))
df_out2 = df_out[mask]
df_out2

,PathId,PointOrder,Iata,Cancelled,Delayed,From,To,Airport,City,State,Country,Latitude,Longitude,PathName,Total,Problematic
2,135,2,IAD,0,1,LAS,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,LAS->IAD,1,1
3,603,2,IAD,0,1,MCO,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,MCO->IAD,1,1
4,604,2,IAD,0,1,MCO,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,MCO->IAD,1,1
5,741,2,IAD,0,1,MDW,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,MDW->IAD,1,1
7,743,2,IAD,0,1,MDW,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,MDW->IAD,1,1
9,745,2,IAD,0,1,MDW,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,MDW->IAD,1,1
10,746,2,IAD,0,1,MDW,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,MDW->IAD,1,1
11,2281,2,IAD,0,1,TPA,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,TPA->IAD,1,1
12,2282,2,IAD,0,1,TPA,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,TPA->IAD,1,1
19,3435,1,IAD,0,1,IAD,MDW,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->MDW,1,1
27,4179,2,IAD,0,1,MDW,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,MDW->IAD,1,1
29,4181,2,IAD,0,1,MDW,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,MDW->IAD,1,1
45,6792,2,IAD,0,1,LAS,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,LAS->IAD,1,1
51,7311,2,IAD,0,1,MDW,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,MDW->IAD,1,1
57,9603,1,IAD,0,1,IAD,MDW,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->MDW,1,1
58,9604,1,IAD,0,1,IAD,MDW,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->MDW,1,1
60,9606,1,IAD,0,1,IAD,MDW,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->MDW,1,1
67,10313,2,IAD,0,1,MDW,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,MDW->IAD,1,1
72,10318,2,IAD,0,1,MDW,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,MDW->IAD,1,1
73,11765,2,IAD,0,1,TPA,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,TPA->IAD,1,1
80,12909,1,IAD,0,1,IAD,MDW,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->MDW,1,1
86,13047,2,IAD,0,1,LAS,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,LAS->IAD,1,1
89,13653,2,IAD,0,1,MDW,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,MDW->IAD,1,1
93,13657,2,IAD,0,1,MDW,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,MDW->IAD,1,1
95,15193,2,IAD,0,1,TPA,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,TPA->IAD,1,1
102,16345,1,IAD,0,1,IAD,MDW,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->MDW,1,1
117,18629,2,IAD,0,1,TPA,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,TPA->IAD,1,1
147,23219,1,IAD,0,1,IAD,MDW,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->MDW,1,1
148,23220,1,IAD,0,1,IAD,MDW,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->MDW,1,1
205,32735,1,IAD,0,1,IAD,MCO,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->MCO,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151984,7004967,2,IAD,0,1,ATL,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,ATL->IAD,1,1
151985,7004968,1,IAD,0,1,IAD,ATL,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->ATL,1,1
151994,7005319,2,IAD,0,1,ATL,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,ATL->IAD,1,1
151995,7005372,1,IAD,0,1,IAD,ATL,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->ATL,1,1
151996,7005425,1,IAD,0,1,IAD,ATL,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->ATL,1,1
151998,7005767,1,IAD,0,1,IAD,ATL,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->ATL,1,1
152000,7005952,1,IAD,0,1,IAD,ATL,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->ATL,1,1
152001,7006153,2,IAD,0,1,ATL,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,ATL->IAD,1,1
152002,7006227,2,IAD,0,1,ATL,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,ATL->IAD,1,1
152003,7006228,1,IAD,0,1,IAD,ATL,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->ATL,1,1
152005,7006248,1,IAD,0,1,IAD,ATL,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->ATL,1,1
152007,7006354,2,IAD,0,1,ATL,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,ATL->IAD,1,1
152008,7006359,2,IAD,0,1,ATL,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,ATL->IAD,1,1
152009,7006374,2,IAD,0,1,ATL,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,ATL->IAD,1,1
152011,7006555,1,IAD,0,1,IAD,ATL,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->ATL,1,1
152012,7006559,2,IAD,0,1,ATL,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,ATL->IAD,1,1
152015,7006684,1,IAD,0,1,IAD,ATL,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->ATL,1,1
152016,7006948,1,IAD,0,1,IAD,ATL,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->ATL,1,1
152020,7007439,1,IAD,0,1,IAD,ATL,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->ATL,1,1
152022,7007536,2,IAD,0,1,ATL,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,ATL->IAD,1,1
152023,7007537,1,IAD,0,1,IAD,ATL,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->ATL,1,1
152025,7007574,2,IAD,0,1,ATL,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,ATL->IAD,1,1
152027,7007664,2,IAD,0,1,ATL,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,ATL->IAD,1,1
152029,7007685,2,IAD,0,1,ATL,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,ATL->IAD,1,1
152031,7007871,1,IAD,0,1,IAD,ATL,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->ATL,1,1
152032,7007875,2,IAD,0,1,ATL,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,ATL->IAD,1,1
152038,7008454,2,IAD,0,1,SLC,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,SLC->IAD,1,1
152041,7008773,2,IAD,0,1,ATL,IAD,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,ATL->IAD,1,1
152043,7008848,1,IAD,0,1,IAD,ATL,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->ATL,1,1
152046,7008894,1,IAD,0,1,IAD,SLC,Washington Dulles International,Chantilly,VA,USA,38.944532,-77.45581,IAD->SLC,1,1

In [17]:
df_summary = df_out.groupby(['PathName']).size()
df_summary

df3 = pd.DataFrame({'FlightsCount' : df_summary}).reset_index()

In [18]:
df3.head(10)

   PathName  FlightsCount
0  ABE->ATL          1706
1  ABE->BHM             2
2  ABE->CLE          1610
3  ABE->CLT           930
4  ABE->CVG           494
5  ABE->DTW          1994
6  ABE->JFK             6
7  ABE->LGA            18
8  ABE->ORD          2850
9  ABE->PHL             4

In [19]:
# Merge df_arch_clean and df_api_clean into df_arch_clean
#df_arch_clean = pd.merge(left=df_arch_clean, right=df_api_clean, how='left', on='tweet_id')

In [20]:
df_summary2 = df_out.groupby(['PathName'])[['Delayed']].sum()
df_summary2.head(10)

          Delayed
PathName
ABE->ATL      366
ABE->BHM        0
ABE->CLE      174
ABE->CLT      106
ABE->CVG       32
ABE->DTW      304
ABE->JFK        6
ABE->LGA       16
ABE->ORD      728
ABE->PHL        2

In [21]:
df_summary3 = df_out.groupby(['PathName'])[['Cancelled']].sum()
df_summary3.head(10)

          Cancelled
PathName
ABE->ATL         28
ABE->BHM          0
ABE->CLE         26
ABE->CLT         14
ABE->CVG          6
ABE->DTW         52
ABE->JFK          0
ABE->LGA          0
ABE->ORD        178
ABE->PHL          0

In [22]:
df_summary4 = df_out.groupby(['PathName']).agg({
    'Total': 'count',
    'Delayed': sum,
    'Cancelled': sum,
    'Problematic': sum})
# Add index as another column
df_summary4['PathName'] = df_summary4.index
df_summary4.head(10)

          Total  Delayed  Cancelled  Problematic  PathName
PathName
ABE->ATL   1706      366         28          394  ABE->ATL
ABE->BHM      2        0          0            0  ABE->BHM
ABE->CLE   1610      174         26          200  ABE->CLE
ABE->CLT    930      106         14          120  ABE->CLT
ABE->CVG    494       32          6           38  ABE->CVG
ABE->DTW   1994      304         52          356  ABE->DTW
ABE->JFK      6        6          0            6  ABE->JFK
ABE->LGA     18       16          0           16  ABE->LGA
ABE->ORD   2850      728        178          906  ABE->ORD
ABE->PHL      4        2          0            2  ABE->PHL

In [23]:
#df_out = pd.merge(left=df, right=df2, how='inner', on='Iata')
df_summary4.info(null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 5366 entries, ABE->ATL to YUM->SLC
Data columns (total 5 columns):
Total          5366 non-null int64
Delayed        5366 non-null int64
Cancelled      5366 non-null int64
Problematic    5366 non-null int64
PathName       5366 non-null object
dtypes: int64(4), object(1)
memory usage: 251.5+ KB

In [24]:
df_summary4.to_csv('data/FlighPaths2008_summary.csv', index=False)

In [ ]:
#df_agg = pd.merge(left=df_summary4, right=df_out[['City','PathName']], how='inner', on='PathName')
#df_agg.drop_duplicates(inplace=True)
#df_agg.info(null_counts=True)

In [ ]:
#df_agg.head(10)